# Generated by Django 4.0.2 on 2022-03-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cats',
            field=models.ManyToManyField(through='news.PostCategory', to='news.Category', verbose_name='Category'),
        ),
    ]
