# Generated by Django 4.0.2 on 2022-05-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_author_id_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('a', 'Статья'), ('n', 'Новость')], default='a', max_length=2),
        ),
    ]
